optimize table achievement_criteria_requirement;
optimize table achievement_reward;
optimize table areatrigger_involvedrelation;
optimize table areatrigger_tavern;
optimize table areatrigger_teleport;
# optimize table area_group_template;
optimize table battleground_events;
optimize table battleground_template;
optimize table battlemaster_entry;
optimize table command;
optimize table conditions;
optimize table creature;
optimize table creature_addon;
optimize table creature_ai_scripts;
optimize table creature_ai_summons;
optimize table creature_battleground;
optimize table creature_conditional_spawn;
# optimize table creature_cooldowns;
optimize table creature_equip_template;
optimize table creature_involvedrelation;
optimize table creature_linking;
optimize table creature_linking_template;
optimize table creature_loot_template;
optimize table creature_model_info;
optimize table creature_model_race;
optimize table creature_movement;
optimize table creature_movement_template;
optimize table creature_onkill_reputation;
optimize table creature_questrelation;
optimize table creature_spawn_entry;
optimize table creature_template;
optimize table creature_template_addon;
optimize table creature_template_classlevelstats;
optimize table creature_template_spells;
# optimize table custom_texts;
optimize table dbscripts_on_creature_death;
optimize table dbscripts_on_creature_movement;
optimize table dbscripts_on_event;
optimize table dbscripts_on_gossip;
optimize table dbscripts_on_go_template_use;
optimize table dbscripts_on_go_use;
optimize table dbscripts_on_quest_end;
optimize table dbscripts_on_quest_start;
optimize table dbscripts_on_relay;
optimize table dbscripts_on_spell;
# optimize table dbscript_random_templates;
optimize table db_version;
optimize table db_version_ytdb;
optimize table disenchant_loot_template;
optimize table exploration_basexp;
optimize table fishing_loot_template;
optimize table gameobject;
optimize table gameobject_addon;
optimize table gameobject_battleground;
optimize table gameobject_involvedrelation;
optimize table gameobject_loot_template;
optimize table gameobject_questrelation;
optimize table gameobject_template;
optimize table game_event;
optimize table game_event_creature;
optimize table game_event_creature_data;
optimize table game_event_gameobject;
optimize table game_event_mail;
optimize table game_event_quest;
optimize table game_event_time;
optimize table game_graveyard_zone;
optimize table game_tele;
optimize table game_weather;
optimize table gossip_menu;
optimize table gossip_menu_option;
optimize table gossip_texts;
# optimize table instance_dungeon_encounters;
optimize table instance_encounters;
optimize table instance_template;
optimize table item_convert;
optimize table item_enchantment_template;
optimize table item_expire_convert;
optimize table item_loot_template;
optimize table item_required_target;
optimize table item_template;
optimize table locales_achievement_reward;
optimize table locales_creature;
optimize table locales_gameobject;
# optimize table locales_gossip_menu_option;
optimize table locales_item;
# optimize table locales_npc_text;
optimize table locales_page_text;
optimize table locales_points_of_interest;
optimize table locales_quest;
# optimize table locales_questgiver_greeting;
# optimize table locales_trainer_greeting;
optimize table mail_level_reward;
optimize table mail_loot_template;
optimize table mangos_string;
optimize table milling_loot_template;
optimize table npc_gossip;
optimize table npc_spellclick_spells;
optimize table npc_text;
optimize table npc_trainer;
optimize table npc_trainer_template;
optimize table npc_vendor;
optimize table npc_vendor_template;
optimize table page_text;
optimize table pet_levelstats;
optimize table pet_name_generation;
optimize table pickpocketing_loot_template;
optimize table playercreateinfo;
optimize table playercreateinfo_action;
# optimize table playercreateinfo_item;
optimize table playercreateinfo_skills;
optimize table playercreateinfo_spell;
optimize table player_classlevelstats;
optimize table player_levelstats;
optimize table player_xp_for_level;
optimize table points_of_interest;
optimize table pool_creature;
optimize table pool_creature_template;
optimize table pool_gameobject;
optimize table pool_gameobject_template;
optimize table pool_pool;
optimize table pool_template;
optimize table prospecting_loot_template;
# optimize table questgiver_greeting;
optimize table quest_poi;
optimize table quest_poi_points;
optimize table quest_template;
optimize table reference_loot_template;
# optimize table reference_loot_template_names;
optimize table reputation_reward_rate;
optimize table reputation_spillover_template;
optimize table reserved_name;
optimize table scripted_areatrigger;
optimize table scripted_event_id;
optimize table script_texts;
optimize table script_waypoint;
optimize table skill_discovery_template;
optimize table skill_extra_item_template;
optimize table skill_fishing_base_level;
optimize table skinning_loot_template;
# optimize table spam_records;
optimize table spell_area;
# optimize table spell_bonus_data;
optimize table spell_chain;
# optimize table spell_cone;
optimize table spell_elixir;
optimize table spell_learn_spell;
optimize table spell_loot_template;
optimize table spell_pet_auras;
optimize table spell_proc_event;
optimize table spell_proc_item_enchant;
optimize table spell_script_target;
optimize table spell_target_position;
# optimize table spell_template;
optimize table spell_threat;
optimize table taxi_shortcuts;
# optimize table trainer_greeting;
optimize table transports;
optimize table vehicle_accessory;
optimize table world_template;